### ISSUE TITLE
Running yo go

### ISSUE THREAD

**Issue by VivaLaPanda** [Bench/generator-go#1]
I am running this generator on the newest version of node and encounter the following error.
When I run 'yo go' I am prompted for my project name, but after hitting enter the generator exits with no code generated.

**Comment by VivaLaPanda** [comment]
http://i.imgur.com/W1Cu3y5.png

**Comment by bench** [comment]
Hi Adrian, 
Thank you for your feedback.
Could you add the **versions** of your **nodejs** and **yeoman** installations to your issue plz ?

`node --version`

`npm list -g | grep yeoman-generator | awk -F@ '{print $2}'` 

I will check it soon ;)

**Comment by VivaLaPanda** [comment]
Sorry for wasting your time, looks like I had an old version of the generator. I updated it through yo itself and that fixed the issue.
