### ISSUE TITLE
Wrong usage of sudo

### ISSUE THREAD

**Issue by creekorful** [Bench/generator-go#4]
Hello there! Thanks for you interesting project.

Just a little notice: in the README.md file you are issuing:

```sh
sudo git clone https://github.com/your_repo/generator-go.git
```

which is wrong, you shouldn't be generally running git as root. (of course there are some use cases).
A plain:

```sh
git clone https://github.com/your_repo/generator-go.git
```

should do the job in a safer manner.

Do you mind updating the README.md so that newcomers won't run git as root?

Thank in advance!

**Comment by bench** [comment]
hello @creekorful,
A thousand apologies for the latency, I have been quite busy lately.
Happy to see your interest for the project, your proposal completely make sense, it was a mistake. fix done and merged :+1:

**Comment by creekorful** [comment]
> hello @creekorful,
> A thousand apologies for the latency, I have been quite busy lately.
> Happy to see your interest for the project, your proposal completely make sense, it was a mistake. fix done and merged +1

No problem at all! Thanks for the fix 😄 

Cheers!
